<div class='login-container-footer' style="background-color: #00ACEC;">
            <div class='container'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='text-center'>
                    <a href='index'>
                      Copyright © 2014 Alatca JSC.
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
