<div class='' style="margin-top:20px;"></div>
    <div class='middle-container  error contrast-background'> <!-- class='wigetdrapdrop' --> 
      <div class='middle-row'>
        <div class='middle-wrapper'>
          <div class='error-container-header'>
            <div class='container'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='text-center'>
                    <i class='icon-question-sign'></i>
                    404
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class='error-container'>
            <div class='container'>
              <div class='row'>
                <div class='col-sm-4 col-sm-offset-4'>
                  <h4 class='text-center title'>Ooops! We can't find what you're looking for.</h4>
                  <p class='text-center'>
                    <small>You can</small>
                  </p>
                  <!--  
                  <form action='search_results.html' method='get'>
                    <div class='form-group'>
                      <div class='input-group controls-group'>
                        <input value="" placeholder="Search..." class="form-control" name="q" type="text" />
                        <span class='input-group-btn'>
                          <button class='btn' type='submit'>
                            <i class='icon-search'></i>
                          </button>
                        </span>
                      </div>
                    </div>
                  </form>
                  -->
                  <p class='text-center'>
                    <small>or</small>
                  </p>
                  <div class='text-center'>
                    <a class='btn btn-md btn-ablock' href='index'>
                      <i class='icon-chevron-left'></i>
                      Go back
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
         
        </div>
    </div>
	<!-- end form -->
	
</div>
<!-- end content-wrapper  -->	
<div class='' style="margin-top:20px;"></div>

	<?php echo $this->action('index','magazinepublish','administrator');?>




   