  <div class='container '>
          <div class='row' id='content-wrapper'>
            <div class='col-xs-12' id="bottom-content">
               <?php //echo " Droad Admin View"?>
               <h1>Droad Admin View</h1>
               <div class="content">
		       		<div class="container-fluid">
		       			<div class="col-md-12 col-xs-12 col-sm-12 col-lg-12 content-ct">
		                		<ul>
		                        		<li class="content-page"><a href="#"></a></li>
		                                <li class="content-design"><a href="#"></a></li>
		                                <li class="content-add"><a href="#"></a></li>
		                                <li class="content-app"><a href="#"></a></li>
		                                <li class="content-setting"><a href="#"></a></li>
		                        </ul>
		                
		                </div>
		       		</div>
		       </div>
       
           </div>
           <?php echo $this->action('index','magazinepublish','administrator');?>
        </div>
</div>		
              
