<ul class="nav nav-list accordion-group">
						<li class="nav-header"><i class="icon-plus icon-white"></i><font>Basic  for CSS</font> <!--  
          <div class="pull-right popover-info"><i class="icon-question-sign "></i>
              <div class="popover fade right">
                <div class="arrow"></div>
                <h3 class="popover-title"><font>Helps Prop</font></h3>
                <div class="popover-content"><font>Following is one of the loạt element US base, you to create style set message  to edit corner in the right of blocks. Leave the more information, please accessible </font><a target="_blank" href="#"><font>Basic for CSS.</font></a></div>
              </div>
            </div>
            --></li>
						<li style="display: none;" class="boxes" id="elmBase">
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"> <i class="icon-remove icon-white"></i> <font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration">
									<button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> 
									<span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"> <font>Style</font><span class="caret"></span></a>
											<ul class="dropdown-menu">
												<li class="active"><a href="#" rel=""><font>Default</font></a></li>
												<li class=""><a href="#" rel="text-left"><font>left</font></a></li>
												<li class=""><a href="#" rel="text-center"><font>center</font></a></li>
												<li class=""><a href="#" rel="text-right"><font>right</font></a></li>
											</ul>
									</span> 
									<span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Remark</font> <span class="caret"></span> </a>
											<ul class="dropdown-menu">
												<li class="active"><a href="#" rel=""><font>Default</font></a></li>
												<li class=""><a href="#" rel="muted"><font>Display</font></a></li>
												<li class=""><a href="#" rel="text-warning"><font>warning</font></a></li>
												<li class=""><a href="#" rel="text-error"><font>error</font></a></li>
												<li class=""><a href="#" rel="text-info"><font>info</font></a></li>
												<li class=""><a href="#" rel="text-success"><font>success</font></a></li>
											</ul>
									</span>
								</span>
								<div class="preview">
									<font>Title</font>
								</div>
								<div class="view">
									<h3 contenteditable="true">
										<font>Lorem ipsum dolor sit amet.</font>
									</h3>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Style text</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class="active"><a href="#" rel=""><font>Default</font></a></li>
											<li class=""><a href="#" rel="text-left"><font>Text
														left</font></a></li>
											<li class=""><a href="#" rel="text-center"><font>Text
														center</font></a></li>
											<li class=""><a href="#" rel="text-right"><font>Text
														right</font></a></li>
										</ul>
								</span> <span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Flag</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class="active"><a href="#" rel=""><font>Default</font></a></li>
											<li class=""><a href="#" rel="muted"><font>Muted</font></a></li>
											<li class=""><a href="#" rel="text-warning"><font>warning</font></a></li>
											<li class=""><a href="#" rel="text-error"><font>error</font></a></li>
											<li class=""><a href="#" rel="text-info"><font>info</font></a></li>
											<li class=""><a href="#" rel="text-success"><font>success</font></a></li>
										</ul>
								</span> <a class="btn btn-mini" href="#" rel="lead"><font>Lead</font></a>
								</span>
								<div class="preview">
									<font>Paragraph</font>
								</div>
								<div class="view" contenteditable="true">
									<p>
										<em><font>Lorem ipsum dolor sit amet, consectetur
												adipiscing elit. Aliquam eget sapien sapien. Curabitur in
												metus urna. In hac habitasse platea dictumst. Phasellus eu
												sem sapien, sed vestibulum velit. Nam purus nibh, lacinia
												non faucibus et, pharetra in dolor. Sed iaculis posuere diam
												ut cursus. Morbi commodo sodales nisi id sodales. Proin
												consectetur, nisi id commodo imperdiet, metus nunc consequat
												lectus, id bibendum diam velit et dui. Proin massa magna,
												vulputate nec bibendum nec, posuere nec lacus. Aliquam mi
												erat, aliquam vel luctus eu, pharetra quis elit. Nulla
												euismod ultrices massa, et feugiat ipsum consequat eu.</font>
									</em></p><em>
								</em></div><em>
							</em></div><em>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Styles </font>
									</button></span>
								<div class="preview">
									<font>Address</font>
								</div>
								<div class="view">
									<address contenteditable="true">
										<strong>Twitter, Inc.</strong><br> 795 Folsom Ave, Suite
										600<br> San Francisco, CA 94107<br> <abbr title="Phone">P:</abbr> (123) 456-7890
									</address>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"> <a class="btn btn-mini" href="#" rel="pull-right"><font>pull right</font></a>
								</span>
								<div class="preview">
									<font>Blockquote</font>
								</div>
								<div class="view clearfix">
									<blockquote contenteditable="true">
										<p>
											<font>Lorem ipsum dolor sit amet, consectetur
												adipiscing elit. Integer posuere erat a ante.</font>
										</p>
										<small><font>Someone famous Source Title</font></small>
									</blockquote>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <a class="btn btn-mini" href="#" rel="unstyled"><font>Unstyled</font></a>
									<a class="btn btn-mini" href="#" rel="inline"><font>inline</font></a>
								</span>
								<div class="preview">
									<font>Unordered List</font>
								</div>
								<div class="view">
									<ul contenteditable="true">
										<li>Lorem ipsum dolor sit amet</li>
										<li>Consectetur adipiscing elit</li>
										<li>Integer molestie lorem at massa</li>
										<li>Facilisis in pretium nisl aliquet</li>
										<li>Nulla volutpat aliquam velit</li>
										<li>Faucibus porta lacus fringilla vel</li>
										<li>Aenean sit amet erat nunc</li>
										<li>Eget porttitor lorem</li>
									</ul>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <a class="btn btn-mini" href="#" rel="unstyled"><font>Unstyled</font></a>
									<a class="btn btn-mini" href="#" rel="inline"><font>inline</font></a>
								</span>
								<div class="preview">
									<font>Ordered List</font>
								</div>
								<div class="view">
									<ol contenteditable="true">
										<li>Lorem ipsum dolor sit amet</li>
										<li>Consectetur adipiscing elit</li>
										<li>Integer molestie lorem at massa</li>
										<li>Facilisis in pretium nisl aliquet</li>
										<li>Nulla volutpat aliquam velit</li>
										<li>Faucibus porta lacus fringilla vel</li>
										<li>Aenean sit amet erat nunc</li>
										<li>Eget porttitor lorem</li>
									</ol>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <a class="btn btn-mini" href="#" rel="dl-horizontal"><font>Horizontal</font></a>
								</span>
								<div class="preview">
									<font>Description</font>
								</div>
								<div class="view">
									<dl contenteditable="true">
										<dt>Description lists</dt>
										<dd>A description list is perfect for defining terms.</dd>
										<dt>Euismod</dt>
										<dd>Vestibulum id ligula porta felis euismod semper eget
											lacinia odio sem nec elit.</dd>
										<dd>Donec id elit non mi porta gravida at eget metus.</dd>
										<dt>Malesuada porta</dt>
										<dd>Etiam porta sem malesuada magna mollis euismod.</dd>
										<dt>Felis euismod semper eget lacinia</dt>
										<dd>Fusce dapibus, tellus ac cursus commodo, tortor
											mauris condimentum nibh, ut fermentum massa justo sit amet
											risus.</dd>
									</dl>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>style table</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class="active"><a href="#" rel=""><font>Default</font></a></li>
											<li class=""><a href="#" rel="table-striped"><font>striped</font></a></li>
											<li class=""><a href="#" rel="table-bordered"><font>bordered</font></a></li>
										</ul>
								</span> <a class="btn btn-mini" href="#" rel="table-hover"><font>hover</font></a>
									<a class="btn btn-mini" href="#" rel="table-condensed"><font>condensed</font></a>
								</span>
								<div class="preview">
									<font>Table</font>
								</div>
								<div class="view">
									<table class="table table-condensed table-hover" contenteditable="true">
										<thead>
											<tr>
												<th>#</th>
												<th>Product</th>
												<th>Payment Taken</th>
												<th>Status</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>1</td>
												<td>TB - Monthly</td>
												<td>01/04/2012</td>
												<td>Default</td>
											</tr>
											<tr class="active">
												<td>1</td>
												<td>TB - Monthly</td>
												<td>01/04/2012</td>
												<td>Approved</td>
											</tr>
											<tr class="success">
												<td>2</td>
												<td>TB - Monthly</td>
												<td>02/04/2012</td>
												<td>Declined</td>
											</tr>
											<tr class="warning">
												<td>3</td>
												<td>TB - Monthly</td>
												<td>03/04/2012</td>
												<td>Pending</td>
											</tr>
											<tr class="danger">
												<td>4</td>
												<td>TB - Monthly</td>
												<td>04/04/2012</td>
												<td>Call in to confirm</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <a class="btn btn-mini" href="#" rel="form-inline"><font>inline</font></a>
								</span>
								<div class="preview">
									<font>Form</font>
								</div>
								<div class="view">
									<form role="form">
										<div class="form-group">
											<label for="exampleInputEmail1">Email address</label> <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
										</div>
										<div class="form-group">
											<label for="exampleInputPassword1">Password</label> <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
										</div>
										<div class="form-group">
											<label for="exampleInputFile">File input</label> <input type="file" id="exampleInputFile">
											<p class="help-block">Example block-level help text here.</p>
										</div>
										<div class="checkbox">
											<label> <input type="checkbox"> Check me out
											</label>
										</div>
										<button type="submit" class="btn btn-default">Submit</button>
									</form>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-danger"><i class="icon-remove icon-white"></i>Delete</a> <span class="drag label label-default"><i class="icon-move"></i>drag</span>
								<span class="configuration"></span>
								<div class="preview">Horizontal Form</div>
								<div class="view">
									<form class="form-horizontal" role="form">
										<div class="form-group">
											<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
											<div class="col-sm-10">
												<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
											</div>
										</div>
										<div class="form-group">
											<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
											<div class="col-sm-10">
												<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
											</div>
										</div>
										<div class="form-group">
											<div class="col-sm-offset-2 col-sm-10">
												<div class="checkbox">
													<label> <input type="checkbox"> Remember me
													</label>
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="col-sm-offset-2 col-sm-10">
												<button type="submit" class="btn btn-default">Sign
													in</button>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <a class="btn btn-mini" href="#" rel="form-inline"><font>inline</font></a>
								</span>
								<div class="preview">
									<font>Search box</font>
								</div>
								<div class="view">
									<form class="form-search">
										<input class="input-medium search-query" type="text">
										<button type="submit" class="btn" contenteditable="true">
											<font>Search</font>
										</button>
									</form>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration"> </span> <span class="configuration"><button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button></span>
								<div class="preview">
									<font>sign in</font>
								</div>
								<div class="view">
									<form class="form-horizontal">
										<div class="control-group">
											<label class="control-label" for="inputEmail" contenteditable="true"><font>Email</font></label>
											<div class="controls">
												<input id="inputEmail" placeholder="Email" type="text">
											</div>
										</div>
										<div class="control-group">
											<label class="control-label" for="inputPassword" contenteditable="true"><font>Password</font></label>
											<div class="controls">
												<input id="inputPassword" placeholder="Password" type="password">
											</div>
										</div>
										<div class="control-group">
											<div class="controls">
												<label class="checkbox" contenteditable="true"> <input type="checkbox"><font>Remember me</font></label>
												<button type="submit" class="btn" contenteditable="true">
													<font>sign in</font>
												</button>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>drag</font></span>
								<span class="configuration">
									<button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> <span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Style</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class="active"><a href="#" rel=""><font>Default</font></a></li>
											<li class=""><a href="#" rel="btn-primary"><font>primary</font></a></li>
											<li class=""><a href="#" rel="btn-info"><font>info</font></a></li>
											<li class=""><a href="#" rel="btn-success"><font>success</font></a></li>
											<li class=""><a href="#" rel="btn-warning"><font>warning</font></a></li>
											<li class=""><a href="#" rel="btn-danger"><font>danger</font></a></li>
											<li class=""><a href="#" rel="btn-inverse"><font>inverse</font></a></li>
											<li class=""><a href="#" rel="btn-link"><font>link</font></a></li>
										</ul>

								</span> <span class="btn-group"> <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Size</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class=""><a href="#" rel="btn-large"><font>large</font></a></li>
											<li class="active"><a href="#" rel=""><font>active</font></a></li>
											<li class=""><a href="#" rel="btn-small"><font>small</font></a></li>
											<li class=""><a href="#" rel="btn-mini"><font>mini</font></a></li>
										</ul>
								</span> <a class="btn btn-mini" href="#" rel="btn-block"><font>block</font></a>
									<a class="btn btn-mini" href="#" rel="disabled"><font>disabled</font></a>
								</span>


								<div class="preview">
									<font>Button</font>
								</div>

								<div class="view">
									<button class="btn" type="button" contenteditable="true">
										<font>button</font>
									</button>
								</div>
							</div>

							<div class="box box-element ui-draggable">
								<a href="#close" class="remove label label-important"><i class="icon-remove icon-white"></i><font>Delete</font></a> <span class="drag label"><i class="icon-move"></i><font>Drag
								</font></span> 
								<span class="configuration"> 
								
									<button type="button" class="btn btn-mini" data-target="#editorModal" role="button" data-toggle="modal">
										<font>Edit content</font>
									</button> 
								<span class="btn-group">
										<a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><font>Style</font><span class="caret"></span></a>
										<ul class="dropdown-menu">
											<li class="active"><a href="#" rel=""><font>Default</font></a></li>
											<li class=""><a href="#" rel="img-rounded"><font>rounded</font></a></li>
											<li class=""><a href="#" rel="img-circle"><font>circle</font></a></li>
											<li class=""><a href="#" rel="img-polaroid"><font>Thumbnail</font></a></li>
										</ul>
								</span>
								</span>
								<div class="preview">
									<font>Images</font>
								</div>
								<div class="view">
									<img alt="140x140" src="img/a.jpg">
								</div>
							</div>
						</em></li><em>
					</em></ul>